backend:
  name: git-gateway
  branch: main
media_folder: 'static/images'
public_folder: '/images'

local_backend: true

collections:
  - name: posts
    label: Blog Posts
    folder: src/lib/posts
    create: true
    extension: "json"
    format: "json"
    fields:
      - name: title
      - name: excerpt
      - name: slug
        required: true
      - name: date
      - name: author
        required: false
      - name: thumbnail
        label: Cover Image
        widget: image
        choose_url: false
        required: false
      - name: body
        widget: markdown
      - label: "Image Gallery"
        name: "image_gallery"
        widget: "list"
        fields:
          - { label: "Image", name: "image", widget: "image" }

  - name: homepage
    label: Home Page Data
    folder: src/lib/homeData
    create: true
    extension: "json"
    format: "json"
    fields:
      - name: Page Title
      - name: Sub Title

  - name: About Page Data
    label: About Page Data
    files:
      - name: about.json
        label: About Page Data
        file: src/lib/aboutData/about.json
        format: "json"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Copy, name: copy, widget: text}
          - label: Images
            name: images
            widget: list
            fields:
              - {label: Images, name: images, widget: image} {label: Images, name: images, widget: image}

  - name: "settings"
    label: "Settings"
    extension: json
    format: json
    files:
        - name: "navigation"
          label: "Navigation"
          file: "src/lib/navigation.json"
          fields:
            - { label: "Navigation Links", name: "links", widget: "list", fields: [
              { label: "Title", name: "title", widget: "string" },
              { label: "URL", name: "url", widget: "string" }
            ] }
