backend:
  name: git-gateway
  branch: main
media_folder: 'static/images'
public_folder: '/images'

local_backend: true

collections:
  - name: posts
    label: Blog Posts
    folder: src/lib/posts
    create: true
    extension: "json"
    format: "json"
    fields:
      - name: title
      - name: excerpt
      - name: slug
        required: true
      - name: date
      - name: author
        required: false
      - name: thumbnail
        label: Cover Image
        widget: image
        choose_url: false
        required: false
      - name: body
        widget: markdown
      - label: "Image Gallery"
        name: "image_gallery"
        widget: "list"
        fields:
          - { label: "Image", name: "image", widget: "image" }

  - name: "settings"
    label: "Settings"
    files:
      - name: "navigation"
        label: "Navigation"
        file: "src/lib/cms/navigation.json"
        fields:
          - { label: "Navigation Links", name: "links", widget: "list", fields: [
            { label: "Title", name: "title", widget: "string" },
            { label: "URL", name: "url", widget: "string" }
          ] }

  - name: "Home Page Data"
    label: "Home Page Data"
    files:
      - name: "Page Content"
        label: "Page Content"
        file: "src/lib/cms/homeData.json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: "content", widget: "markdown" } # Changed to 'markdown' for body content
          - { label: "Hero Image", name: "heroImage", widget: "image" } # Field names typically don't have spaces

  - name: "About Page Data"
    label: "About Page Data"
    file: "src/lib/cms/aboutData.json"
    fields:
      - {label: "Title", name: "Title" widget: "string"}
      - {label: "Content", name: "Content", widget: "markdown"}
      - {label: "Hero Image", name: "Hero Image", widget:"image"} 
