
backend:
  name: git-gateway
  branch: main
media_folder: 'static/images'
public_folder: '/images'

local_backend: true

collections:
  - name: posts
    label: Blog Posts
    folder: src/lib/posts
    create: true
    extension: "json"
    format: "json"
    fields:
      - name: title
      - name: excerpt
      - name: slug
        required: true
      - name: date
      - name: author
        required: false
      - name: thumbnail
        label: Cover Image
        widget: image
        choose_url: false
        required: false
      - name: body
        widget: markdown
      - label: "Image Gallery"
        name: "image_gallery"
        widget: "list"
        fields:
          - { label: "Image", name: "image", widget: "image" }
  - name: "settings"
    label: "Settings"
    extension: "json"
    format: "json"
    files:
      - file: "src/lib/cms/settings/navigation.json" # Adjust the file path as needed
        label: "Navigation"
        name: "Navigation"
        fields:
          - { label: "Navigation Links", name: "links", widget: "list", fields: [
            { label: "Title", name: "title", widget: "string" },
            { label: "URL", name: "url", widget: "string" }
          ] }
  - name: "Home Page Data"
    label: "Home Page Data"
    extension: "json"
    format: "json"
    files:
      - file: "src/lib/cms/home/homeData.json" # Adjust the file path as needed
        label: "Page Content"
        name: "Page Content"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: "content", widget: "markdown" }
          - { label: "Hero Image", name: "heroImage", widget: "image" }

  - name: "About Page Data"
    label: "About Page Data"
    extension: "json"
    format: "json"
    files: 
      - file: "src/lib/cms/about/aboutData.json" # Adjust the file path as needed
        label: "Page Data"
        name: "Page Data"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Content", name: "content", widget: "markdown"}
          - {label: "Hero Image", name: "heroImage", widget: "image"}
