backend:
  name: git-gateway
  branch: main
media_folder: 'static/images'
public_folder: '/images'

local_backend: true

collections:
  - name: posts
    label: Blog Posts
    folder: src/lib/posts
    create: true
    extension: "json"
    format: "json"
    fields:
      - name: title
      - name: excerpt
      - name: slug
        required: true
      - name: date
      - name: author
        required: false
      - name: thumbnail
        label: Cover Image
        widget: image
        choose_url: false
        required: false
      - name: body
        widget: markdown
      - label: "Image Gallery"
        name: "image_gallery"
        widget: "list"
        fields:
          - { label: "Image", name: "image", widget: "image" }
  - name: homepage
    label: Home Page Data
    folder: src/lib/homeData
    create: true
    extension: "json"
    format: "json"
    fields:
      - name: Page Title
      - name: Sub Title

  - name: About
    label: About Page Data
    folder: src/lib/aboutData
    create: true
    extension: "json"
    format: "json"
    fields:
      - name: Page Title
      - {label: Copy, name: copy, widget: text}